export const HOME = '/'
export const BUILD = '/build'
export const EXPEDITIONS = '/expeditions'
export const CATACOMBS = '/catacombs'
export const OSSUARY = '/ossuary'
export const SOUL_WELL = '/soul-well'
export const BATTLEMENTS = '/battlements'
export const CHARNEL_HOUSE = '/charnel-house'
