name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    name: Install node_modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ hashFiles('**/yarn.lock') }}
            yarn-
      - run: yarn --frozen-lockfile
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ hashFiles('**/yarn.lock') }}
            yarn-
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test
  build:
    name: Build app and run E2E tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@master
      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ hashFiles('**/yarn.lock') }}
            yarn-
      - run: NODE_ENV=test yarn build:noprecache
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/
      - name: Restore Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: cypress-binary-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            cypress-binary-${{ hashFiles('**/yarn.lock') }}
            cypress-binary-
      - run: yarn cypress install
      - run: yarn e2e
      - name: Upload build
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: cypress
          path: cypress/videos/
